/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TarifFraisDossierList { 
    readonly id: number;
    produit: number;
    quantite_min?: number;
    quantite_max?: number | null;
    prix_unitaire: string;
}

