/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Statut4feEnum } from './statut4feEnum';


export interface ActionPlanifieeDetail { 
    readonly id: number;
    created_at?: string;
    updated_at?: string;
    date_execution: string;
    statut: Statut4feEnum;
    created_by?: number | null;
    updated_by?: number | null;
    agenda: number;
    client: number;
    plan_action: number;
}
export namespace ActionPlanifieeDetail {
}


