/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `FAV` - Avis favorable * `DEF` - Avis défavorable * `NOF` - Avis non fourni
 */
export const AvisEnum = {
    Fav: 'FAV',
    Def: 'DEF',
    Nof: 'NOF'
} as const;
export type AvisEnum = typeof AvisEnum[keyof typeof AvisEnum];

