/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChangeStatutFicheTechniqueResponse { 
    fiche_technique: number;
    nouveau_statut: number;
}

