/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Dashboard { 
    nombreFacturesDirection: number;
    montantTotalDesFactures: number;
    nombreFacturesPosition: number;
    nombreDevisDirection: number;
    montantTotalDesDevis: number;
    nombreDevisPosition: number;
    montantDevisPosition: number;
    nombreProduitsDirection: number;
}

