/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ElementFacturationRecuStatutEnum } from './elementFacturationRecuStatutEnum';
import { TypeFraisEnum } from './typeFraisEnum';


export interface ElementFacturationRecu { 
    readonly id: number;
    fiche_technique: number;
    type_frais?: TypeFraisEnum;
    statut?: ElementFacturationRecuStatutEnum;
    readonly created_at: string;
    readonly updated_at: string;
}
export namespace ElementFacturationRecu {
}


