/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `CREE` - Créé * `TRAITE` - Traité
 */
export const ElementFacturationRecuStatutEnum = {
    Cree: 'CREE',
    Traite: 'TRAITE'
} as const;
export type ElementFacturationRecuStatutEnum = typeof ElementFacturationRecuStatutEnum[keyof typeof ElementFacturationRecuStatutEnum];

