/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ElementFacturationRecuCreeList { 
    readonly id: number;
    id_client: number;
    client: string;
    compte_comptable: string;
    element_facturation_recu_id: number;
    categorie_produit_id: number;
    type_frais: string;
    fiche_technique_id: number;
    date_soumission: string;
}

