/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FactureEncaissement { 
    facture_id: number | null;
    montant_affecte: string;
    date_affectation: string;
    readonly id: number;
}

