/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatutFicheTechnique } from './statutFicheTechnique';
import { FicheTechniqueDocument } from './ficheTechniqueDocument';
import { FicheTechniqueProduit } from './ficheTechniqueProduit';
import { AvisEnum } from './avisEnum';


export interface FicheTechnique { 
    readonly id: number;
    client: number;
    /**
     * Dénomination sociale
     */
    readonly client_nom: string;
    direction: number;
    utilisateur?: number | null;
    produits?: Array<{ [key: string]: any; }>;
    readonly produits_detail: Array<FicheTechniqueProduit>;
    date_creation?: string;
    position?: number;
    position_direction?: number | null;
    categorie_produit?: number;
    statut?: StatutFicheTechnique | null;
    documents?: Array<string>;
    readonly documents_detail: Array<FicheTechniqueDocument>;
    objet?: string | null;
    commentaire?: string | null;
    avis?: AvisEnum;
    duree?: number | null;
    date_fin?: string | null;
    date_debut?: string | null;
    periode?: string | null;
}
export namespace FicheTechnique {
}


