/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenererDevisGarantieResponse { 
    devis_id: number;
    fiche_technique: number;
    total: string;
    nombre_lignes: number;
}

