/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenererFactureFromDevisResponse { 
    facture_id: number;
    devis: number;
    total: string;
    nombre_lignes: number;
}

