/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeGroupeRecouvrementEnum } from './typeGroupeRecouvrementEnum';
import { PrioriteEnum } from './prioriteEnum';


export interface GroupeRecouvrementList { 
    readonly id: number;
    libelle: string;
    priorite: PrioriteEnum;
    type_groupe_recouvrement: TypeGroupeRecouvrementEnum;
}
export namespace GroupeRecouvrementList {
}


