/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ListeFraisFicheTechniqueProduit { 
    readonly id: number;
    categorie_produit_id: number;
    categorie_produit: string;
    type_frais: string;
    id_ftp: number;
    fiche_technique_id: number;
    produit_id: number;
    code_produit: string;
    description_produit: string;
    prix_unitaire: number;
    quantite: number;
    total: number;
}

