/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeModeleRelanceEnum } from './typeModeleRelanceEnum';


export interface ModeleRelanceList { 
    readonly id: number;
    type_modele_relance: TypeModeleRelanceEnum;
    version?: number;
}
export namespace ModeleRelanceList {
}


