/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeModeleRelanceEnum } from './typeModeleRelanceEnum';


export interface PatchedModeleRelanceDetail { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    type_modele_relance?: TypeModeleRelanceEnum;
    contenu?: string;
    version?: number;
    created_by?: number | null;
    updated_by?: number | null;
}
export namespace PatchedModeleRelanceDetail {
}


