/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeGroupeRecouvrementEnum } from './typeGroupeRecouvrementEnum';
import { PrioriteEnum } from './prioriteEnum';


export interface PatchedGroupeRecouvrementDetail { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    libelle?: string;
    priorite?: PrioriteEnum;
    type_groupe_recouvrement?: TypeGroupeRecouvrementEnum;
    criteres?: string | null;
    created_by?: number | null;
    updated_by?: number | null;
    clients?: Array<number>;
}
export namespace PatchedGroupeRecouvrementDetail {
}


