/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedCategorieProduit { 
    readonly id?: number;
    code?: string;
    libelle?: string;
    description?: string;
    created_at?: string;
    updated_at?: string;
}

