/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FactureEncaissement } from './factureEncaissement';


export interface PatchedEncaissement { 
    readonly id?: number;
    date_encaissement?: string;
    montant?: number;
    affecte?: number;
    penalites?: number;
    solde_non_affecte?: number;
    reference?: string;
    objet?: string | null;
    mode_paiement?: number;
    client?: number;
    affectations?: Array<FactureEncaissement>;
}

