/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneFacture } from './ligneFacture';
import { EtatEnum } from './etatEnum';
import { TypeFraisEnum } from './typeFraisEnum';


export interface PatchedFacture { 
    readonly id?: number;
    reference?: string | null;
    objet?: string | null;
    commentaire?: string | null;
    date_echeance?: string;
    date_reception?: string | null;
    montant?: number;
    etat?: EtatEnum;
    client?: number;
    /**
     * Dénomination sociale
     */
    readonly client_nom?: string;
    /**
     * Numero de compte comptable
     */
    readonly compte_comptable?: string | null;
    devis?: number | null;
    direction_technique?: number;
    fiche_technique?: number | null;
    readonly lignes_facture?: Array<LigneFacture>;
    position_direction?: number | null;
    position?: number;
    readonly categorie_produit?: string;
    type_frais?: TypeFraisEnum;
    periode?: string | null;
}
export namespace PatchedFacture {
}


