/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedFicheTechniqueProduit { 
    readonly id?: number;
    produit?: number;
    fiche_technique_id?: number;
    readonly produit_libelle?: string;
    quantite?: number | null;
    prix_unitaire?: string | null;
    designation?: string | null;
    total?: string | null;
}

