/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedParametre { 
    readonly id?: number;
    key?: string;
    value?: string;
    description?: string | null;
    is_active?: boolean;
    readonly created_at?: string;
    readonly updated_at?: string;
}

