/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypePlanActionEnum } from './typePlanActionEnum';
import { DeclencheurEnum } from './declencheurEnum';


export interface PlanActionList { 
    readonly id: number;
    groupe: number;
    ordre: number;
    type_plan_action: TypePlanActionEnum;
    declencheur: DeclencheurEnum;
    nb_jours: number;
}
export namespace PlanActionList {
}


