/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModeEnum } from './modeEnum';
import { TypePlanActionEnum } from './typePlanActionEnum';
import { DeclencheurEnum } from './declencheurEnum';


export interface PlanActionDetail { 
    readonly id: number;
    created_at?: string;
    updated_at?: string;
    ordre: number;
    type_plan_action: TypePlanActionEnum;
    declencheur: DeclencheurEnum;
    nb_jours: number;
    mode: ModeEnum;
    created_by?: number | null;
    updated_by?: number | null;
    groupe: number;
    modele?: number | null;
}
export namespace PlanActionDetail {
}


