/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PrintParams { 
    readonly id: number;
    nom_institution?: string;
    pays?: string;
    devise?: string;
    lieu?: string;
    logo?: string | null;
    timbre?: string | null;
    date_format?: string;
    readonly created_at: string;
}

