/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Produit { 
    readonly id: number;
    libelle: string;
    description?: string | null;
    categorieProduit: number;
}

