/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecouvDashboardClient { 
    readonly id: number;
    client_id: number;
    type_client: string;
    client: string;
    compte_comptable?: string | null;
    email?: string | null;
    telephone?: string | null;
    nbre_factures_impayes?: number | null;
    total_du?: number | null;
    avance_du?: number | null;
}

