/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecouvListeEncaissements { 
    readonly id: number;
    id_client: number;
    type_client: string;
    client: string;
    email?: string | null;
    telephone?: string | null;
    encaissement_id: number;
    date_encaissement: string;
    montant_encaisse: number;
    montant_affecte: number;
    montant_restant: number;
    statut_affectation: string;
    mode_paiement_id: number;
    mode_paiement_libelle?: string | null;
}

