/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReleveCompteClient { 
    id: number;
    type_ligne: string;
    date_echeance: string;
    reference?: string | null;
    montant: number;
}

