/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `DYNAMIQUE` - Dynamique * `MANUEL` - Manuel
 */
export const TypeGroupeRecouvrementEnum = {
    Dynamique: 'DYNAMIQUE',
    Manuel: 'MANUEL'
} as const;
export type TypeGroupeRecouvrementEnum = typeof TypeGroupeRecouvrementEnum[keyof typeof TypeGroupeRecouvrementEnum];

