/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `FD` - Frais de dossier * `GA` - Garantie * `RD` - Redevance annuelle * `RC` - Redevance de contrôle * `EL` - Electricité * `LO` - Loyer * `IN` - Inscription * `RA` - Restauration * `DA` - Dossier d\'Appel d\'Offre 
 */
export const TypeFraisEnum = {
    Fd: 'FD',
    Ga: 'GA',
    Rd: 'RD',
    Rc: 'RC',
    El: 'EL',
    Lo: 'LO',
    In: 'IN',
    Ra: 'RA',
    Da: 'DA'
} as const;
export type TypeFraisEnum = typeof TypeFraisEnum[keyof typeof TypeFraisEnum];

