/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `APPELER` - Appeler * `EMAIL` - Email * `SMS` - SMS * `COURRIER` - Courrier * `SE_DEPLACER` - Se déplacer * `INFORMER_DIRECTION` - Informer la direction technique * `TRANSFERER_CONTENTIEUX` - Transférer en contentieux
 */
export const TypePlanActionEnum = {
    Appeler: 'APPELER',
    Email: 'EMAIL',
    Sms: 'SMS',
    Courrier: 'COURRIER',
    SeDeplacer: 'SE_DEPLACER',
    InformerDirection: 'INFORMER_DIRECTION',
    TransfererContentieux: 'TRANSFERER_CONTENTIEUX'
} as const;
export type TypePlanActionEnum = typeof TypePlanActionEnum[keyof typeof TypePlanActionEnum];

