/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `FD` - Frais de dossier * `GA` - Garantie * `RD` - Redevance annuelle * `RC` - Redevance de contrôle
 */
export const TypeFraisEnum = {
    Fd: 'FD',
    Ga: 'GA',
    Rd: 'RD',
    Rc: 'RC'
} as const;
export type TypeFraisEnum = typeof TypeFraisEnum[keyof typeof TypeFraisEnum];

