/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkflowHistory { 
    readonly id: number;
    instance: number;
    from_step?: number | null;
    readonly from_step_code: string;
    to_step?: number | null;
    readonly to_step_code: string;
    transition?: number | null;
    occurred_at?: string;
    actor?: string;
    comment?: string | null;
}

