/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ZoneCouvertureDetail { 
    readonly id: number;
    code: string;
    libelle: string;
    categorie_produit: number;
}

