// src/app/authentication/operations.ts

export const OPS = {
  // --- Fiches techniques ---
  CREER_FICHE: 'CREER_FICHE',
  LIRE_FICHE: 'LIRE_FICHE',
  MODIFIER_FICHE: 'MODIFIER_FICHE',
  TRANSMETTRE_FICHE: 'TRANSMETTRE_FICHE',
  REJETER_FICHE: 'REJETER_FICHE',
  AVIS_TECHNIQUE_FICHE: 'AVIS_TECHNIQUE_FICHE',
  RETRAIT_FICHE: 'RETRAIT_FICHE',

  // --- Factures / Devis ---
  GENERER_DEVIS_FACTURE: 'GENERER_DEVIS_FACTURE',
  MODIFIER_DEVIS_FACTURE: 'MODIFIER_DEVIS_FACTURE',
  EDITER_DEVIS_FACTURE: 'EDITER_DEVIS_FACTURE',
  ANNULER_DEVIS_FACTURE: 'ANNULER_DEVIS_FACTURE',

  // --- Encaissements ---
  ENCAISSER: 'ENCAISSER',
  LIRE_ENCAISSEMENT: 'LIRE_ENCAISSEMENT',
  EDITER_RECU_ENCAISSEMENT: 'EDITER_RECU_ENCAISSEMENT',
  EXPORTER_ENCAISSEMENT: 'EXPORTER_ENCAISSEMENT',

  // --- Recouvrement ---
  RECOUVREMENT_GERER_PLANS: 'RECOUVREMENT_GERER_PLANS',
  RECOUVREMENT_GERER_DECLENCHEURS: 'RECOUVREMENT_GERER_DECLENCHEURS',
  RECOUVREMENT_GERER_PROMESSES: 'RECOUVREMENT_GERER_PROMESSES',
  RECOUVREMENT_GERER_GROUPES: 'RECOUVREMENT_GERER_GROUPES',
  RECOUVREMENT_GERER_AGENDA: 'RECOUVREMENT_GERER_AGENDA',
  RECOUVREMENT_GERER_MODELES_LETTRES: 'RECOUVREMENT_GERER_MODELES_LETTRES',

  // --- Administration ---
  ADMIN_GERER_ROLES: 'ADMIN_GERER_ROLES',
  ADMIN_GERER_UTILISATEURS: 'ADMIN_GERER_UTILISATEURS',
  ADMIN_DEBLOQUER_COMPTE: 'ADMIN_DEBLOQUER_COMPTE',
  GERER_REFERENTIELS_GENERAUX: 'GERER_REFERENTIELS_GENERAUX',
  GERER_ELEMENTS_FREQUENCES: 'GERER_ELEMENTS_FREQUENCES',
  GERER_PARAMETRES_TARIFS: 'GERER_PARAMETRES_TARIFS',

  // --- Paiement ---
  PAIEMENT_INITIER: 'PAIEMENT_INITIER'
} as const;

export type OperationCode = typeof OPS[keyof typeof OPS];

export const ALL_OPERATION_CODES = Object.values(OPS) as OperationCode[];
export const ALL_OPERATION_CODES_SET = new Set<OperationCode>(ALL_OPERATION_CODES);
